categories:
  腾讯:
    dns: tls://dot.pub https://doh.pub/dns-query
    urls:
      - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/tencent.list
      - https://raw.githubusercontent.com/lztxi/ADH/refs/heads/main/config/tencent.list

  阿里:
    dns: https://dns.alidns.com/dns-query
    urls:
      - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/alibaba.list

  字节跳动:
    dns: 180.184.1.1 180.184.2.2
    urls:
      - https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/bytedance.list
